#pragma config(Sensor, dgtl1,  ultrasonicleft, sensorSONAR_cm)
#pragma config(Sensor, dgtl3,  ultrasonicright, sensorSONAR_cm)
#pragma config(Motor,  port1,           frontleft,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           frontright,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           backleft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           backright,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void move(int power) {
  motor[frontleft] = power;
  motor[frontright] = power;
  motor[backleft] = power;
  motor[backright] = power;
}


void turn(int power) {
  //positive for clockwise/right, negative for counterclockwise/left
  motor[frontleft] = power;
  motor[frontright] = -power;
  motor[backleft] = power;
  motor[backright] = -power;

}

void avoid() {
  //avoids walls
  while(SensorValue[ultrasonicleft] < 10) {
    turn(90);
  }

  while(SensorValue[ultrasonicright] < 10) {
    turn(-90);
  }
}
