#pragma config(Sensor, dgtl1,  ultrasonicleft, sensorSONAR_cm)
#pragma config(Sensor, dgtl3,  ultrasonicright, sensorSONAR_cm)
#pragma config(Motor,  port1,           frontleft,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           frontright,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           backleft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           backright,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main() {
  while(true) {
    move(90);
    while(SensorValue[ultrasonicleft] < 20 || SensorValue[ultrasonicright] < 20) {
      //if any two of the ultrasonic sensors detect that the bot is too close to the wall, the bot will turn right.
      turn(90);
    }
    wait1msec(10); //even if both sensors detect they are not close to the wall, the bot will keep turning to try and competely turn away from the wall, turning for x msec after being clear of the wall.
    //The bot will continue moving.
  }

    
