#pragma config(Sensor, dgtl1,  encoderL,       sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  encoderR,       sensorQuadEncoder)
#pragma config(Motor,  port5,           motorL,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           motorR,        tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// PID using optical shaft encoder
//
// Shaft encoder has 360 pulses per revolution
//

#define PID_SENSOR_INDEXL    encoderL
#define PID_SENSOR_SCALEL    1

#define PID_SENSOR_INDEXR    encoderR
#define PID_SENSOR_SCALER    1

#define PID_MOTOR_INDEXL     motorL
#define PID_MOTOR_SCALEL     -1

#define PID_MOTOR_INDEXR   motorR
#define PID_MOTOR_SCALER     -1

#define PID_DRIVE_MAX       120
#define PID_DRIVE_MIN     (-120)

#define PID_INTEGRAL_LIMIT  50

// These could be constants but leaving
// as variables allows them to be modified in the debugger "live"
float  pid_Kp = 0.3;
float  pid_Ki = 0.0;
float  pid_Kd = 0.05;

static int   pidRunning = 1;
static float pidRequestedValueL;
static float pidRequestedValueR;

const unsigned int TrueSpeed[128] =
{
  0, 0, 10, 10, 10, 10, 11, 11, 11, 11,
  11, 12, 12, 12, 12, 12, 13, 13, 13, 13,
  13, 13, 14, 14, 14, 14, 14, 15, 15, 15,
  15, 16, 16, 16, 16, 16, 16, 17, 17, 17,
  17, 17, 18, 18, 18, 18, 19, 19, 19, 19,
  20, 20, 20, 20, 20, 21, 21, 21, 21, 21,
  22, 22, 22, 23, 23, 23, 24, 24, 24, 24,
  25, 25, 25, 26, 26, 26, 27, 27, 27, 28,
  28, 28, 29, 29, 30, 31, 31, 32, 32, 33,
  33, 34, 34, 34, 35, 35, 36, 37, 38, 40,
  41, 41, 42, 43, 44, 45, 47, 48, 50, 51,
  51, 52, 52, 53, 55, 56, 57, 58, 60, 62,
  66, 69, 74, 84, 85, 85, 126, 127
};
/*-----------------------------------------------------------------------------*/
/*                                                                             */
/*  pid control task                                                           */
/*                                                                             */
/*-----------------------------------------------------------------------------*/

task pidController1()
{
    float  pidSensorCurrentValue;

    float  pidError;
    float  pidLastError;
    float  pidIntegral;
    float  pidDerivative;
    float  pidDrive;

    // If we are using an encoder then clear it
    if( SensorType [PID_SENSOR_INDEXL ] == sensorQuadEncoder )
        SensorValue [PID_SENSOR_INDEXL ] = 0;

    // Init the variables - thanks Glenn :)
    pidLastError  = 0;
    pidIntegral   = 0;

    while( true )
        {
        // Is PID control active ?
        if( pidRunning )
            {
            // Read the sensor value and scale
            pidSensorCurrentValue = SensorValue[ PID_SENSOR_INDEXL ] * PID_SENSOR_SCALEL;

            // calculate error
            pidError = pidSensorCurrentValue - pidRequestedValueL;

            // integral - if Ki is not 0
            if( pid_Ki != 0 )
                {
                // If we are inside controlable window then integrate the error
                if( abs(pidError) < PID_INTEGRAL_LIMIT )
                    pidIntegral = pidIntegral + pidError;
                else
                    pidIntegral = 0;
                }
            else
                pidIntegral = 0;

            // calculate the derivative
            pidDerivative = pidError - pidLastError;
            pidLastError  = pidError;

            // calculate drive
            pidDrive = (pid_Kp * pidError) + (pid_Ki * pidIntegral) + (pid_Kd * pidDerivative);

            // limit drive
            if( pidDrive > PID_DRIVE_MAX )
                pidDrive = PID_DRIVE_MAX;
            if( pidDrive < PID_DRIVE_MIN )
                pidDrive = PID_DRIVE_MIN;

            // send to motor
            motor [PID_MOTOR_INDEXL ] = TrueSpeed[abs(pidDrive * PID_MOTOR_SCALEL)]*-sgn(pidDrive);
            }
        else
            {
            // clear all
            pidError      = 0;
            pidLastError  = 0;
            pidIntegral   = 0;
            pidDerivative = 0;
            motor [PID_MOTOR_INDEXL ] = 0;
            }

        // Run at 50Hz
        wait1Msec( 25 );
        }
}

task pidController2()
{
    float  pidSensorCurrentValue;

    float  pidError;
    float  pidLastError;
    float  pidIntegral;
    float  pidDerivative;
    float  pidDrive;

    // If we are using an encoder then clear it
    if( SensorType [PID_SENSOR_INDEXR ] == sensorQuadEncoder )
        SensorValue [PID_SENSOR_INDEXR ] = 0;

    // Init the variables - thanks Glenn :)
    pidLastError  = 0;
    pidIntegral   = 0;

    while( true )
        {
        // Is PID control active ?
        if( pidRunning )
            {
            // Read the sensor value and scale
            pidSensorCurrentValue = SensorValue[ PID_SENSOR_INDEXR ] * PID_SENSOR_SCALER;

            // calculate error
            pidError = pidSensorCurrentValue - pidRequestedValueR;

            // integral - if Ki is not 0
            if( pid_Ki != 0 )
                {
                // If we are inside controlable window then integrate the error
                if( abs(pidError) < PID_INTEGRAL_LIMIT )
                    pidIntegral = pidIntegral + pidError;
                else
                    pidIntegral = 0;
                }
            else
                pidIntegral = 0;

            // calculate the derivative
            pidDerivative = pidError - pidLastError;
            pidLastError  = pidError;

            // calculate drive
            pidDrive = (pid_Kp * pidError) + (pid_Ki * pidIntegral) + (pid_Kd * pidDerivative);

            // limit drive
            if( pidDrive > PID_DRIVE_MAX )
                pidDrive = PID_DRIVE_MAX;
            if( pidDrive < PID_DRIVE_MIN )
                pidDrive = PID_DRIVE_MIN;

            // send to motor
            motor [PID_MOTOR_INDEXR ] = TrueSpeed[abs(pidDrive * PID_MOTOR_SCALER)]*-sgn(pidDrive);
            }
        else
            {
            // clear all
            pidError      = 0;
            pidLastError  = 0;
            pidIntegral   = 0;
            pidDerivative = 0;
            motor [PID_MOTOR_INDEXR ] = 0;
            }

        // Run at 50Hz
        wait1Msec( 25 );
        }
}

/*-----------------------------------------------------------------------------*/
/*                                                                             */
/*  main task                                                                  */
/*                                                                             */
/*-----------------------------------------------------------------------------*/

task main()
{
wait1Msec(1000);
    // send the motor off somewhere
    pidRequestedValueL = 2450;
    pidRequestedValueR = 2450;
    SensorValue[encoderL] = 0;
    SensorValue[encoderR] = 0;

    // start the PID task
    startTask( pidController1 );
    startTask( pidController2 );
    //(pidRequestedValueL!=SensorValue[encoderL]){break;}
    wait1Msec(10000);


}
