#pragma config(Motor,  port5,           left,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           right,         tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


//Port 5: Left drive
//Port 6: Right Drive
task main()
{



}
