#pragma config(Motor,  port1,           motor1,        tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           motor2,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           motor3,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           motor4,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           motor5,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           motor6,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           motor7,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           motor8,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           motor9,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          motor10,       tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	//Runs all motors for any given port.
	while(true)
	{
		motor[motor1]=100;
		motor[motor2]=100;
		motor[motor2]=100;
		motor[motor3]=100;
		motor[motor4]=100;
		motor[motor5]=100;
		motor[motor6]=100;
		motor[motor7]=100;
		motor[motor8]=100;
		motor[motor9]=100;
		motor[motor10]=100;

	}

}
