#pragma config(Sensor, dgtl1,  button1,        sensorTouch)
#pragma config(Motor,  port4,           motor4,        tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true)
	{
//if button is not pressed, motor is off.
		if(SensorValue (button1) == 0)
		{motor[motor4] = 0;}
//if button is pressed, motor is on
		if (SensorValue(button1) == 1)
		{motor[motor4] = 100;}
	}

}
