#pragma config(Sensor, dgtl1,  encoder1,       sensorQuadEncoder)
#pragma config(Motor,  port4,           motor4,        tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	wait1Msec(2000); //2 second delay
	SensorValue[encoder1]=0; //resets the encoder. We do not want the encoder starting at some revolution value.
	while(SensorValue[encoder1] < 1800)
	{
		//Before 1800 rotations, keep running the motor.
		//After 1800 rotations, stop the motor.
		motor[motor4] = 75;
	}


}
