#pragma config(Motor,  port4,           motor4,        tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	motor[motor4] = 100; //Set motor at some speed.
	wait1Msec(5000); //After 5 seconds
	motor[motor4] = 0; //Stop motor

}
