#pragma config(Sensor, in1,    POT1,           sensorPotentiometer)
#pragma config(Motor,  port4,           motor4,        tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true)
	{
		//Maps the range of the potentinometer 0 to 4096 to 0-127 to set the speed of the motor
		motor[motor4] = (SensorValue(POT1)/32);

	}
}
