#pragma config(Motor,  port5,           leftDrive,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           rightDrive,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           spinner,          tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void update();
void arcadeStyleDrive();
void spinnerControl();

typedef struct {
    //joystick
    int leftY;
    int rightX;

    //Spinner
    int spinLeft;
    int spinRight;
    
} buttons;

buttons controller;


void update() {
    //Run this continously to retrieve controller values.
    //joystick
    controller.leftY = vexRT[Ch3];
    controller.rightX = vexRT[Ch2];
    
    //Spinner
        //Top left shoulder button
    controller.spinLeft = vexRT[Btn5U];
        //Top right shoulder button
    controller.spinRight = vexRT[Btn6U];

}


void arcadeStyleDrive() {
    motor[leftDrive]=(controller.leftY + controller.rightX)/2;
    motor[rightDrive]=(controller.leftY - controller.rightX)/2;
}

void spinnerControl() {
    if(controller.spinLeft) {
        motor[spinner] = -127;
    } else if {
        motor[spinner] = 127;
    } else {
        motor[spinner] = 0;
    }
}

